***************
*** 1,6 ****
  VERSION = 3
  PATCHLEVEL = 0
- SUBLEVEL = 0
  EXTRAVERSION =
  NAME = Sneaky Weasel
  
--- 1,6 ----
  VERSION = 3
  PATCHLEVEL = 0
+ SUBLEVEL = 9
  EXTRAVERSION =
  NAME = Sneaky Weasel
  
